version: '2'
services:
  mattgowie.com:
    container_name: mattgowie.com
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    networks:
      - dockernet
networks:
  dockernet:
    external: true
